export const CREATED = 201;
export const UPDATED = 200;


export const AUTH_USER = 'auth_user';
export const INVALIDATE_USER = 'invalidate_user';
export const AUTH_ERROR = 'auth_error';
export const SET_DIRECTION = "SET_DIRECTION";
export const LOAD_TRANSLATION = 'LOAD_TRANSLATION';
export const INIT_AUTH_USER = 'INIT_AUTH_USER';

//FieldState
export const GET_FIELD_STATES = 'GET_FIELD_STATES';
export const GET_FIELD_FOR_MAP = 'GET_FIELD_FOR_MAP';
export const GET_FIELD_CROP_CYCLES = 'GET_FIELD_CROP_CYCLES';

export const SELECT_FIELD = 'SELECT_FIELD';
export const EDIT_FIELD_POLYGON = 'EDIT_FIELD_POLYGON';
export const RELOADING_MAP = 'RELOADING_MAP';
export const SET_SELECTED_FIELD_INDEX = 'SET_SELECTED_FIELD_INDEX';
export const POST_FIELD = 'POST_FIELD';
export const GET_FIELD_STATISTICS = 'GET_FIELD_STATISTICS';
export const TOGGLE_FIELD_LAYER = 'TOGGLE_FIELD_LAYER';
export const SET_MAP_BASE_LAYER = 'SET_MAP_BASE_LAYER';
export const SET_DOMAIN_STATUS_FILTER = 'SET_DOMAIN_STATUS_FILTER';
export const GET_GG_ADMIN_AREAS = 'GET_GG_ADMIN_AREAS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const SET_CROP_TYPE = 'SET_CROP_TYPE';
export const SET_NAVIGATE_ON_CRITICAL = 'SET_NAVIGATE_ON_CRITICAL';

export const SET_MAP_PESTS = 'SET_MAP_PESTS';
export const SET_MAP_REF_DATE = 'SET_MAP_REF_DATE';
export const SET_MAP_INFECTION_LEVEL = 'SET_MAP_INFECTION_LEVEL';
export const SET_MAP_TIME_RANGE = 'SET_MAP_TIME_RANGE';
export const SET_MAP_ACTIVITIES = 'SET_MAP_ACTIVITIES';

//Account Actions
export const GET_GLOBAL_DATA = 'GET_GLOBAL_DATA';
export const SET_EXIT_ROUTE = 'SET_EXIT_ROUTE';
export const BY_BUSINESS_UPDATED = 'BY_BUSINESS_UPDATED';
export const SET_QUICK_ADD = 'SET_QUICK_ADD';



//Site
export const SELECT_SITE = 'SELECT_SITE';
export const SITE_UPDATE = 'SITE_UPDATE';
export const SITE_CREATE = 'SITE_CREATE';
export const GET_SITE = 'GET_SITE';
export const DELETE_SITE = 'DELETE_SITE';
export const GET_SITES = 'GET_SITES';
export const CLEAR_SITE = 'CLEAR_SITE';

//Link
export const SELECT_LINK = 'SELECT_LINK';
export const LINK_UPDATE = 'LINK_UPDATE';
export const LINK_CREATE = 'LINK_CREATE';
export const GET_LINK = 'GET_LINK';
export const DELETE_LINK = 'DELETE_LINK';
export const GET_LINKS = 'GET_LINKS';
export const CLEAR_LINK = 'CLEAR_LINK';

export const SELECT_PARENT_FIELD = 'SELECT_PARENT_FIELD';
export const GET_PARENT_FIELD = 'GET_PARENT_FIELD';
export const GET_PARENT_FIELDS = 'GET_PARENT_FIELDS';
export const DELETE_PARENT_FIELD = 'DELETE_PARENT_FIELD';
export const PARENT_FIELD_UPDATED = 'PARENT_FIELD_UPDATED';
export const PARENT_FIELD_CREATED = 'PARENT_FIELD_CREATED';
export const CLEAR_PARENT_FIELD = 'CLEAR_PARENT_FIELD';

export const SELECT_SEASON = 'SELECT_SEASON';
export const EDIT_MAP = 'EDIT_MAP';

export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_PLAN_ACTIVITIES = 'GET_PLAN_ACTIVITIES';
export const CLEAR_ACTIVITIES = 'CLEAR_ACTIVITIES';

export const SET_FETCHING_ACTIVITIES = 'SET_FETCHING_ACTIVITIES';
export const SET_FETCHING_PLAN_ACTIVITIES = 'SET_FETCHING_PLAN_ACTIVITIES';


export const GET_WAYBILLS = 'GET_WAYBILLS';
export const SET_WAYBILLS = 'SET_WAYBILLS';
export const SET_ACTIVITY = 'SET_ACTIVITY';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const NEW_ACTIVITY = 'NEW_ACTIVITY';
export const ACTIVITY_CREATED = 'ACTIVITY_CREATED';
export const ACTIVITY_UPDATED = 'ACTIVITY_UPDATED';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const MARK_DELETE_ACTIVITY = 'MARK_DELETE_ACTIVITY';

export const SET_ACTIVITY_TABLE_FREE_TEXT_DEEP_SEARCH = 'SET_ACTIVITY_TABLE_FREE_TEXT_DEEP_SEARCH';
export const SET_ACTIVITY_TABLE_FILTER = 'SET_ACTIVITY_TABLE_FILTER';
export const SET_DOMAIN_HISTORY_TABLE_FILTER = 'SET_DOMAIN_HISTORY_TABLE_FILTER';
export const SET_PLAN_ACTIVITY_TABLE_FILTER = 'SET_PLAN_ACTIVITY_TABLE_FILTER';
export const SET_ACTIVITY_TABLE_START = 'SET_ACTIVITY_TABLE_START';
export const SET_PLAN_ACTIVITY_TABLE_START = 'SET_PLAN_ACTIVITY_TABLE_START';
export const SET_ACTIVITY_TABLE_END = 'SET_ACTIVITY_TABLE_END';
export const SET_PLAN_ACTIVITY_TABLE_END = 'SET_PLAN_ACTIVITY_TABLE_END';
export const SET_ACTIVITY_TABLE_FREE_TEXT = 'SET_ACTIVITY_TABLE_FREE_TEXT';
export const SET_PLAN_ACTIVITY_TABLE_FREE_TEXT = 'SET_PLAN_ACTIVITY_TABLE_FREE_TEXT';
export const SET_ACTIVITY_TABLE_FETCH = 'SET_ACTIVITY_TABLE_FETCH';
export const SET_PLAN_ACTIVITY_TABLE_FETCH = 'SET_PLAN_ACTIVITY_TABLE_FETCH';
export const SET_ACTIVITY_TABLE_SORTING = 'SET_ACTIVITY_TABLE_SORTING';
export const SET_PLAN_ACTIVITY_TABLE_SORTING = 'SET_PLAN_ACTIVITY_TABLE_SORTING';
export const SET_ACTIVITY_TABLE_CURRENT_PAGE = 'SET_ACTIVITY_TABLE_CURRENT_PAGE';
export const SET_PLAN_ACTIVITY_TABLE_CURRENT_PAGE = 'SET_PLAN_ACTIVITY_TABLE_CURRENT_PAGE';
export const GET_DOMAIN_ACTIVITY_GPS_LOG = 'GET_DOMAIN_ACTIVITY_GPS_LOG';
export const GET_PEST_GEO_JSON = 'GET_PEST_GEO_JSON';
export const GET_WAYPOINTS_GEO_JSON = 'GET_WAYPOINTS_GEO_JSON';
export const GET_TRACKER_GPS = 'GET_TRACKER_GPS';

export const GET_APPROVAL = 'GET_APPROVAL';
export const CLEAR_APPROVAL = 'CLEAR_APPROVAL';
export const UPDATE_APPROVAL_PRINTED = 'UPDATE_APPROVAL_PRINTED';
export const APPROVAL_UPDATED = 'APPROVAL_UPDATED';

export const GET_PROCUREMENTS = 'GET_PROCUREMENTS';
export const SET_FETCHING_PROCUREMENTS = 'SET_FETCHING_PROCUREMENTS';
export const SET_SUPPLIER_INVOICE = 'SET_SUPPLIER_INVOICE';
export const SET_SUPPLIER_MONTH_INVOICE = 'SET_SUPPLIER_MONTH_INVOICE';

export const GET_PROCUREMENT = 'GET_PROCUREMENT';
export const DUPLICATE_PROCUREMENT = 'DUPLICATE_PROCUREMENT';
export const SET_PROCUREMENT = 'SET_PROCUREMENT';
export const PROCUREMENT_CREATED = 'PROCUREMENT_CREATED';
export const PROCUREMENT_UPDATED = 'PROCUREMENT_UPDATED';
export const DELETE_PROCUREMENT = 'DELETE_PROCUREMENT';
export const SET_PROCUREMENT_FILTER = 'SET_PROCUREMENT_FILTER';
export const SET_PROCUREMENT_FILTER_FREE_TEXT = 'SET_PROCUREMENT_FILTER_FREE_TEXT';
export const SET_PROCUREMENT_FILTER_START = 'SET_PROCUREMENT_FILTER_START';
export const SET_PROCUREMENT_FILTER_END = 'SET_PROCUREMENT_FILTER_END';
export const SET_PROCUREMENT_CURRENT_PAGE = 'SET_PROCUREMENT_CURRENT_PAGE';
export const SET_PROCUREMENT_SORTING = 'SET_PROCUREMENT_SORTING';


export const GET_RISK_ASSESSMENT = 'GET_RISK_ASSESSMENT';
export const SET_RISK_ASSESSMENT = 'SET_RISK_ASSESSMENT';
export const RISK_ASSESSMENT_CREATED = 'RISK_ASSESSMENT_CREATED';
export const RISK_ASSESSMENT_UPDATED = 'RISK_ASSESSMENT_UPDATED';
export const DELETE_RISK_ASSESSMENT = 'DELETE_RISK_ASSESSMENT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_VARIANT = 'SET_MESSAGE_VARIANT';


export const DRAW_MODE = 'DRAW_MODE';
export const SET_POLYGON = 'SET_POLYGON';

export const FIELD_TABLE_SORT = 'FIELD_SORT'
export const GET_FIELD = 'GET_FIELD'
export const DELETE_FIELD = 'DELETE_FIELD'
export const GET_FIELDS = 'GET_FIELDS'
export const FIELD_CREATED = 'FIELD_CREATED'
export const FIELD_UPDATED = 'FIELD_UPDATED'
export const GET_FIELD_IN_POLYGONS = 'GET_FIELD_IN_POLYGONS'
export const CLEAR_FIELD = 'CLEAR_FIELD'
export const GET_FIELD_IN_CUTIVARS = 'GET_FIELD_IN_CUTIVARS'


export const SELECT_DOMAIN = 'SELECT_DOMAIN';
export const DELETE_DOMAIN = 'DELETE_DOMAIN';
export const GET_DOMAIN = 'GET_DOMAIN';
export const GET_DOMAINS_BY_YEAR = 'GET_DOMAINS_BY_YEAR';
export const GET_SELECTION_DOMAINS_BY_YEAR = 'GET_SELECTION_DOMAINS_BY_YEAR';
export const SPLIT_DOMAIN = 'SPLIT_DOMAIN';
export const GET_DOMAIN_ESTIMATE_PRODUCE = 'GET_DOMAIN_ESTIMATE_PRODUCE';
export const SET_SEASON_PARAM = 'SET_SEASON_PARAM';



export const DOMAIN_CREATED = 'DOMAIN_CREATED';
export const DOMAIN_UPDATED = 'DOMAIN_UPDATED';
export const DOMAIN_END_CROP = 'DOMAIN_END_CROP';
export const DOMAIN_START_CROP = 'DOMAIN_START_CROP';
export const DOMAIN_SPLITTED = 'DOMAIN_SPLITTED';


export const SET_FIELD_FILTER = 'SET_FIELD_FILTER';
export const SET_YEAR_FILTER = 'SET_YEAR_FILTER';
export const SET_SELECTION_YEAR_FILTER = 'SET_SELECTION_YEAR_FILTER';
export const SET_DOMAIN_VIEW_SIZE = 'SET_DOMAIN_VIEW_SIZE';
export const SET_FIELD_FREE_TEXT = 'SET_FIELD_FREE_TEXT';



export const GET_DASHBOARD_PLANTATION = 'GET_DASHBOARD_PLANTATION';
export const GET_DASHBOARD_DOMAIN = 'GET_DASHBOARD_DOMAIN';
export const CLEAR_DASHBOARD = 'CLEAR_DASHBOARD';
export const GET_DASHBOARD_FINANCIAL = 'GET_DASHBOARD_FINANCIAL';
export const GET_DASHBOARD_FINANCIAL2 = 'GET_DASHBOARD_FINANCIAL2';
export const GET_DASHBOARD_QUANTITATIVE = 'GET_DASHBOARD_QUANTITATIVE';
export const GET_DASHBOARD_QUANTITATIVE2 = 'GET_DASHBOARD_QUANTITATIVE2';
export const GET_CROP_ROTATION = 'GET_CROP_ROTATION';
export const SET_FETCHING_FINANCIAL_DASHBOARD = 'SET_FETCHING_FINANCIAL_DASHBOARD';
export const SET_FETCHING_QUANTITATIVE_DASHBOARD = 'SET_FETCHING_QUANTITATIVE_DASHBOARD';
export const SAVE_SEASON_DATA = 'SAVE_SEASON_DATA';


export const GET_USERS = 'GET_USERS';
export const GET_AUTHORIZATIONS = 'GET_AUTHORIZATIONS';
export const TOGGLE_AUTHORIZATION = 'TOGGLE_AUTHORIZATION';
export const SET_USER_MAP_CENTER = 'SET_USER_MAP_CENTER';
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const SAVE_USER_TAGS = 'SAVE_USER_TAGS';
export const GET_USER_TAGS = 'GET_USER_TAGS';
export const SET_TAGS_AUTHORIZATIONS = 'SET_TAGS_AUTHORIZATIONS';

export const EDIT_USER = 'EDIT_USER';

export const USER_SAVED = 'USER_SAVED';
export const BUSINESS_SAVED = 'BUSINESS_SAVED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';

export const GET_CUSTOMER_AND_SUPPLIERS = 'GET_CUSTOMER_AND_SUPPLIERS';
export const GET_CUSTOMER_OR_SUPPLIER = 'GET_CUSTOMER_OR_SUPPLIER';
export const SELECT_CUSTOMER_OR_SUPPLIER = 'SELECT_CUSTOMER_OR_SUPPLIER';
export const DELETE_CUSTOMER_OR_SUPPLIER = 'DELETE_CUSTOMER_OR_SUPPLIER';
export const CUSTOMER_OR_SUPPLIER_CREATED = 'CUSTOMER_OR_SUPPLIER_CREATED';
export const CUSTOMER_OR_SUPPLIER_UPDATED = 'CUSTOMER_OR_SUPPLIER_UPDATED';

export const GET_EXECUTORS = 'GET_EXECUTORS';
export const GET_EXECUTOR = 'GET_EXECUTOR';
export const SELECT_EXECUTOR = 'SELECT_EXECUTOR';
export const DELETE_EXECUTOR = 'DELETE_EXECUTOR';
export const EXECUTOR_CREATED = 'EXECUTOR_CREATED';
export const EXECUTOR_UPDATED = 'EXECUTOR_UPDATED';

export const GET_ENERGIES = 'GET_ENERGIES';


export const GET_EQUIPMENTS = 'GET_EQUIPMENTS';
export const GET_EQUIPMENT = 'GET_EQUIPMENT';
export const SELECT_EQUIPMENT = 'SELECT_EQUIPMENT';
export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT';
export const EQUIPMENT_CREATED = 'EQUIPMENT_CREATED';
export const EQUIPMENT_UPDATED = 'EQUIPMENT_UPDATED';

export const GET_VARIETIES = 'GET_VARIETIES';
export const GET_VARIETY = 'GET_VARIETY';
export const SELECT_VARIETY = 'SELECT_VARIETY';
export const DELETE_VARIETY = 'DELETE_VARIETY';
export const VARIETY_CREATED = 'VARIETY_CREATED';
export const VARIETY_UPDATED = 'VARIETY_UPDATED';

export const GET_FERTILIZERS = 'GET_FERTILIZERS';
export const GET_FERTILIZER = 'GET_FERTILIZER';
export const SELECT_FERTILIZER = 'SELECT_FERTILIZER';
export const DELETE_FERTILIZER = 'DELETE_FERTILIZER';
export const FERTILIZER_CREATED = 'FERTILIZER_CREATED';
export const FERTILIZER_UPDATED = 'FERTILIZER_UPDATED';

export const GET_PESTICIDES = 'GET_PESTICIDES';
export const GET_PESTICIDE = 'GET_PESTICIDE';
export const SELECT_PESTICIDE = 'SELECT_PESTICIDE';
export const DELETE_PESTICIDE = 'DELETE_PESTICIDE';
export const PESTICIDE_CREATED = 'PESTICIDE_CREATED';
export const PESTICIDE_UPDATED = 'PESTICIDE_UPDATED';
export const GET_FIELD_IN_PRODUCTS = 'GET_FIELD_IN_PRODUCTS';


export const GET_COMPOSTS = 'GET_COMPOSTS';
export const GET_COMPOST = 'GET_COMPOST';
export const SELECT_COMPOST = 'SELECT_COMPOST';
export const DELETE_COMPOST = 'DELETE_COMPOST';
export const COMPOST_CREATED = 'COMPOST_CREATED';
export const COMPOST_UPDATED = 'COMPOST_UPDATED';

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENT = 'GET_INGREDIENT';
export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const INGREDIENT_CREATED = 'INGREDIENT_CREATED';
export const INGREDIENT_UPDATED = 'INGREDIENT_UPDATED';

export const GET_DISINFECTANTS = 'GET_DISINFECTANTS';
export const GET_DISINFECTANT = 'GET_DISINFECTANT';
export const SELECT_DISINFECTANT = 'SELECT_DISINFECTANT';
export const DELETE_DISINFECTANT = 'DELETE_DISINFECTANT';
export const DISINFECTANT_CREATED = 'DISINFECTANT_CREATED';
export const DISINFECTANT_UPDATED = 'DISINFECTANT_UPDATED';

export const GET_WATER_SOURCES = 'GET_WATER_SOURCES';
export const GET_WATER_SOURCE = 'GET_WATER_SOURCE';
export const SELECT_WATER_SOURCE = 'SELECT_WATER_SOURCE';
export const DELETE_WATER_SOURCE = 'DELETE_WATER_SOURCE';
export const WATER_SOURCE_CREATED = 'WATER_SOURCE_CREATED';
export const WATER_SOURCE_UPDATED = 'WATER_SOURCE_UPDATED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_CREATED = 'PRODUCT_CREATED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';

export const GET_ACCESSORIES = 'GET_ACCESSORIES';
export const GET_ACCESSORY = 'GET_ACCESSORY';
export const SELECT_ACCESSORY = 'SELECT_ACCESSORY';
export const DELETE_ACCESSORY = 'DELETE_ACCESSORY';
export const ACCESSORY_CREATED = 'ACCESSORY_CREATED';
export const ACCESSORY_UPDATED = 'ACCESSORY_UPDATED';

export const GET_CROPS = 'GET_CROPS';
export const GET_CROP = 'GET_CROP';
export const SELECT_CROP = 'SELECT_CROP';
export const DELETE_CROP = 'DELETE_CROP';
export const CROP_CREATED = 'CROP_CREATED';
export const CROP_UPDATED = 'CROP_UPDATED';
export const CLEAR_CROP = 'CLEAR_CROP';

export const CLEAR_RESOURCE = 'CLEAR_RESOURCE';


export const GET_BASE_CROPS = 'GET_BASE_CROPS';
export const GET_BASE_CROP = 'GET_BASE_CROP';
export const SELECT_BASE_CROP = 'SELECT_BASE_CROP';
export const DELETE_BASE_CROP = 'DELETE_BASE_CROP';
export const CROP_BASE_CREATED = 'CROP_BASE_CREATED';
export const CROP_BASE_UPDATED = 'CROP_BASE_UPDATED';

export const GET_WAREHOUSES = 'GET_WAREHOUSES';
export const GET_WAREHOUSE = 'GET_WAREHOUSE';
export const SELECT_WAREHOUSE = 'SELECT_WAREHOUSE';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';
export const WAREHOUSE_CREATED = 'WAREHOUSE_CREATED';
export const WAREHOUSE_UPDATED = 'WAREHOUSE_UPDATED';
export const CLEAR_WAREHOUSE = 'CLEAR_WAREHOUSE';


export const GET_ACTIVITY_DEFS = 'GET_ACTIVITY_DEFS';
export const GET_ACTIVITY_DEF = 'GET_ACTIVITY_DEF';
export const SELECT_ACTIVITY_DEF = 'SELECT_ACTIVITY_DEF';
export const DELETE_ACTIVITY_DEF = 'DELETE_ACTIVITY_DEF';
export const CLEAR_ACTIVITY_DEF = 'CLEAR_ACTIVITY_DEF';

export const ACTIVITY_DEF_CREATED = 'ACTIVITY_DEF_CREATED';
export const ACTIVITY_DEF_UPDATED = 'ACTIVITY_DEF_UPDATED';
export const GET_ACTIVITY_DEF_TYPES = 'GET_ACTIVITY_DEF_TYPES';
export const GET_ACTIVITY_DEF_TYPE = 'GET_ACTIVITY_DEF_TYPE';
export const SELECT_ACTIVITY_DEF_TYPE = 'SELECT_ACTIVITY_DEF_TYPE';
export const DELETE_ACTIVITY_DEF_TYPE = 'DELETE_ACTIVITY_DEF_TYPE';
export const ACTIVITY_DEF_TYPE_CREATED = 'ACTIVITY_DEF_TYPE_CREATED';
export const ACTIVITY_DEF_TYPE_UPDATED = 'ACTIVITY_DEF_TYPE_UPDATED';
export const CLEAR_ACTIVITY_DEF_TYPE = 'CLEAR_ACTIVITY_DEF_TYPE';

export const GET_CONTAINERS = 'GET_CONTAINERS';
export const GET_CONTAINER = 'GET_CONTAINER';
export const SELECT_CONTAINER = 'SELECT_CONTAINER';
export const DELETE_CONTAINER = 'DELETE_CONTAINER';
export const CONTAINER_CREATED = 'CONTAINER_CREATED';
export const CONTAINER_UPDATED = 'CONTAINER_UPDATED';
export const CLEAR_CONTAINER = 'CLEAR_CONTAINER';

//inventory
export const SELECT_INVENTORY_UPDATE = 'SELECT_INVENTORY_UPDATE';
export const INVENTORY_UPDATE_UPDATED = 'INVENTORY_UPDATE_UPDATED';
export const INVENTORY_UPDATE_CREATED = 'INVENTORY_UPDATE_CREATED';
export const GET_INVENTORY_UPDATE = 'GET_INVENTORY_UPDATE';
export const GET_INVENTORY = 'GET_INVENTORY';
export const GET_STOCK_MOVEMENTS = 'GET_STOCK_MOVEMENTS';

export const CLEAR_INVENTORY_UPDATE = 'CLEAR_INVENTORY_UPDATE';

export const DELETE_INVENTORY_UPDATE = 'DELETE_INVENTORY_UPDATE';
export const SET_FETCH_INVENTORY_UPDATE = 'SET_FETCH_INVENTORY_UPDATE';

export const GET_INVENTORY_UPDATES = 'GET_INVENTORY_UPDATES';
export const GET_CURRENT_INVENTORY = 'GET_CURRENT_INVENTORY';

export const GET_DATA_MODULES = 'GET_DATA_MODULES';
export const IMPORT_FILE = 'IMPORT_FILE';
export const CLEAR_IMPORT_EXPORT_RESULT = 'CLEAR_IMPORT_EXPORT_RESULT';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILES = 'UPLOAD_FILES';
export const GET_FILES = 'GET_FILES';
export const DELETE_FILE = 'DELETE_FILE';
export const UPLOADING = 'UPLOADING';
export const MOVE_FILE = 'MOVE_FILE';

export const GET_WATER_SYS = 'GET_WATER_SYS';
export const SYNC_WATER_SYS = 'SYNC_WATER_SYS';
export const UPDATE_VALVE = 'UPDATE_VALVE';
export const VALVE_DUPLICATED = 'VALVE_DUPLICATED';
export const VALVE_DELETED = 'VALVE_DELETED';
export const LIST_WATER_SYS_ACCOUNTS = 'LIST_WATER_SYS_ACCOUNTS';
export const IMPORT_ACCUMULATIONS = 'IMPORT_ACCUMULATIONS';
export const SELECT_VALVE = 'SELECT_VALVE';
export const SET_ACTIVE_VALVES = 'SET_ACTIVE_VALVES';


export const CLEAR_WATER_SYS = 'CLEAR_WATER_SYS';
export const WATER_SYS_CONFIG_UPDATE = 'WATER_SYS_CONFIG_UPDATE';
export const WATER_SYS_CONFIG_CREATE = 'WATER_SYS_CONFIG_CREATE';
export const DELETE_WATER_SYS_CONFIG = 'DELETE_WATER_SYS_CONFIG';

export const GET_FERTILIZER_HUBS = 'GET_FERTILIZER_HUBS';
export const GET_FERTILIZER_HUB = 'GET_FERTILIZER_HUB';
export const SELECT_FERTILIZER_HUB = 'SELECT_FERTILIZER_HUB';
export const DELETE_FERTILIZER_HUB = 'DELETE_FERTILIZER_HUB';
export const FERTILIZER_HUB_CREATED = 'FERTILIZER_HUB_CREATED';
export const FERTILIZER_HUB_UPDATED = 'FERTILIZER_HUB_UPDATED';
export const CLEAR_FERTILIZER_HUB = 'CLEAR_FERTILIZER_HUB';
export const FERTILIZER_HUB_VALVES_UPDATED = 'FERTILIZER_HUB_VALVES_UPDATED';

export const GET_REPORT_META_DATA = 'GET_REPORT_META_DATA';
export const EMAIL_REPORT = 'EMAIL_REPORT';


export const GET_TARIFF = 'GET_TARIFF';
export const SELECT_TARIFF = 'SELECT_TARIFF';
export const DELETE_TARIFF = 'DELETE_TARIFF';
export const SET_TARIFF = 'SET_TARIFF';
export const TARIFF_CREATED = 'TARIFF_CREATED';
export const TARIFF_UPDATED = 'TARIFF_UPDATED';
export const SET_FETCH_TARIFFS = 'SET_FETCH_TARIFFS';
export const CLEAR_TARIFF = 'CLEAR_TARIFF';
export const DUPLICATE_TARIFF = 'DUPLICATE_TARIFF';

export const GET_MAINTENANCE = 'GET_MAINTENANCE';
export const DUPLICATE_MAINTENANCE = 'DUPLICATE_MAINTENANCE';
export const CLEAR_MAINTENANCE = 'CLEAR_MAINTENANCE';
export const SELECT_MAINTENANCE = 'SELECT_MAINTENANCE';
export const DELETE_MAINTENANCE = 'DELETE_MAINTENANCE';
export const SET_MAINTENANCE = 'SET_MAINTENANCE';
export const MAINTENANCE_CREATED = 'MAINTENANCE_CREATED';
export const MAINTENANCE_UPDATED = 'MAINTENANCE_UPDATED';
export const SET_FETCH_MAINTENANCE = 'SET_FETCH_MAINTENANCE';

export const GET_RISKS = 'GET_RISKS';
export const GET_RISK = 'GET_RISK';
export const SELECT_RISK = 'SELECT_RISK';
export const DELETE_RISK = 'DELETE_RISK';
export const RISK_UPDATED = 'RISK_UPDATED';
export const RISK_CREATED = 'RISK_CREATED';


export const GET_PESTS = 'GET_PESTS';
export const GET_PEST = 'GET_PEST';
export const SELECT_PEST = 'SELECT_PEST';
export const DELETE_PEST = 'DELETE_PEST';
export const PEST_CREATED = 'PEST_CREATED';
export const PEST_UPDATED = 'PEST_UPDATED';
export const CLEAR_PEST = 'CLEAR_PEST';


export const GET_PESTICIDE_LISTS = 'GET_PESTICIDE_LISTS';
export const GET_PESTICIDE_LIST = 'GET_PESTICIDE_LIST';
export const SELECT_PESTICIDE_LIST = 'SELECT_PESTICIDE_LIST';
export const CLEAR_PESTICIDE_LIST = 'CLEAR_PESTICIDE_LIST';
export const SELECT_PESTICIDE_LIST_PESTICIDE = 'SELECT_PESTICIDE_LIST_PESTICIDE';
export const DELETE_PESTICIDE_LIST = 'DELETE_PESTICIDE_LIST';
export const DUPLICATE_PESTICIDE_LIST = 'DUPLICATE_PESTICIDE_LIST';

export const PESTICIDE_LIST_CREATED = 'PESTICIDE_LIST_CREATED';
export const PESTICIDE_LIST_UPDATED = 'PESTICIDE_LIST_UPDATED';
export const PESTICIDE_LIST_PESTICIDE_CREATED = 'PESTICIDE_LIST_PESTICIDE_CREATED';
export const PESTICIDE_LIST_PESTICIDE_UPDATED = 'PESTICIDE_LIST_PESTICIDE_UPDATED';
export const DELETE_PESTICIDE_LIST_PESTICIDE = 'DELETE_PESTICIDE_LIST_PESTICIDE';

export const GET_BUSINESSES = 'GET_BUSINESSES';
export const GET_BUSINESS = 'GET_BUSINESS';
export const GET_BUSINESS_USERS = 'GET_BUSINESS_USERS';
export const SELECT_BUSINESS = 'SELECT_BUSINESS';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';
export const BUSINESS_CREATED = 'BUSINESS_CREATED';
export const BUSINESS_UPDATED = 'BUSINESS_UPDATED';
export const CLEAR_BUSINESS = 'CLEAR_BUSINESS';
export const GET_FEILDIN_GROUPS = 'GET_FEILDIN_GROUPS';
export const GET_FEILDIN_COMPANIES = 'GET_FEILDIN_COMPANIES';

export const GET_LINKED_GROWERS = 'GET_LINKED_GROWERS';


export const SELECT_BUSINESS_USER = 'SELECT_BUSINESS_USER';
export const DELETE_BUSINESS_USER = 'DELETE_BUSINESS_USER';
export const BUSINESS_USER_CREATED = 'BUSINESS_USER_CREATED';
export const BUSINESS_USER_UPDATED = 'BUSINESS_USER_UPDATED';
export const CLEAR_BUSINESS_USER = 'CLEAR_BUSINESS_USER';


export const SEARCH_AGROMONITORING = 'SEARCH_AGROMONITORING';
export const NDVI_HISTORY = 'NDVI_HISTORY';
export const GET_SOIL_DATA = 'GET_SOIL_DATA';
export const GET_UVI = 'GET_UVI';
export const GET_WEATHER = 'GET_WEATHER';
export const GET_ACCUMUATED_TEMP = 'GET_ACCUMUATED_TEMP';
export const GET_ACCUMUATED_PRECIP = 'GET_ACCUMUATED_PRECIP';
export const ADD_NDVI_HISTORY = 'ADD_NDVI_HISTORY';
export const CHANGE_IMAGERY_DATE = 'CHANGE_IMAGERY_DATE';
export const CHANGE_NDVI_PALETTE = 'CHANGE_NDVI_PALETTE';
export const GET_SOIL_HISTOTY = 'GET_SOIL_HISTOTY';


export const SET_TABLE_PAGE_SIZE = 'SET_TABLE_PAGE_SIZE';


//GIS Actions
export const GET_GIS_POLYGONS = 'GET_GIS_POLYGONS';
export const SET_GIS_POLYGON_ID = 'SET_GIS_POLYGON_ID';
export const GET_GIS_POLYGON_ID = 'GET_GIS_POLYGON_ID';
export const SET_GIS_POLYGON_NAME = 'SET_GIS_POLYGON_NAME';
export const GET_GIS_POLYGON_NAME = 'GET_GIS_POLYGON_NAME';
export const GET_GIS_POLYGON_ATTRIBUTES = 'GET_GIS_POLYGON_ATTRIBUTES';
export const DELETE_GIS_DATA = 'DELETE_GIS_DATA';



//Tags
export const SELECT_TAG = 'SELECT_TAG';
export const TAG_UPDATE = 'TAG_UPDATE';
export const TAG_CREATE = 'TAG_CREATE';
export const GET_TAG = 'GET_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const GET_TAGS = 'GET_TAGS';
export const CLEAR_TAG = 'CLEAR_TAG';

//RESOURCE_EXTERNAL_CODE
export const SELECT_RESOURCE_EXTERNAL_CODE = 'SELECT_RESOURCE_EXTERNAL_CODE';
export const RESOURCE_EXTERNAL_CODE_UPDATE = 'RESOURCE_EXTERNAL_CODE_UPDATE';
export const RESOURCE_EXTERNAL_CODE_CREATE = 'RESOURCE_EXTERNAL_CODE_CREATE';
export const GET_RESOURCE_EXTERNAL_CODE = 'GET_RESOURCE_EXTERNAL_CODE';
export const DELETE_RESOURCE_EXTERNAL_CODE = 'DELETE_RESOURCE_EXTERNAL_CODE';
export const GET_RESOURCE_EXTERNAL_CODES = 'GET_RESOURCE_EXTERNAL_CODES';
export const CLEAR_RESOURCE_EXTERNAL_CODE = 'CLEAR_RESOURCE_EXTERNAL_CODE';

//ALERT
export const SELECT_ALERT = 'SELECT_ALERT';
export const ALERT_UPDATE = 'ALERT_UPDATE';
export const ALERT_CREATE = 'ALERT_CREATE';
export const GET_ALERT = 'GET_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';
export const GET_ALERTS = 'GET_ALERTS';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SET_EXECUTE_ALERT = 'SET_EXECUTE_ALERT';

//COMPOUND
export const SELECT_COMPOUND = 'SELECT_COMPOUND';
export const UPDATE_COMPOUND = 'UPDATE_COMPOUND';
export const CREATE_COMPOUND = 'CREATE_COMPOUND';
export const GET_COMPOUND = 'GET_COMPOUND';
export const DELETE_COMPOUND = 'DELETE_COMPOUND';
export const GET_COMPOUNDS = 'GET_COMPOUNDS';
export const CLEAR_COMPOUND = 'CLEAR_COMPOUND';




//Active Ingredeient
export const SELECT_ACTIVE_INGREDIENT = 'SELECT_ACTIVE_INGREDIENT';
export const ACTIVE_INGREDIENT_UPDATE = 'ACTIVE_INGREDIENT_UPDATE';
export const ACTIVE_INGREDIENT_CREATE = 'ACTIVE_INGREDIENT_CREATE';
export const GET_ACTIVE_INGREDIENT = 'GET_ACTIVE_INGREDIENT';
export const DELETE_ACTIVE_INGREDIENT = 'DELETE_ACTIVE_INGREDIENT';
export const GET_ACTIVE_INGREDIENTS = 'GET_ACTIVE_INGREDIENTS';
export const CLEAR_ACTIVE_INGREDIENT = 'CLEAR_ACTIVE_INGREDIENT';

//CROP_GENUS
export const SELECT_CROP_GENUS = 'SELECT_CROP_GENUS';
export const CROP_GENUS_UPDATE = 'CROP_GENUS_UPDATE';
export const CROP_GENUS_CREATE = 'CROP_GENUS_CREATE';
export const GET_CROP_GENUSES = 'GET_CROP_GENUSES';
export const DELETE_CROP_GENUS = 'DELETE_CROP_GENUS';
export const GET_CROP_GENUS = 'GET_CROP_GENUS';
export const CLEAR_CROP_GENUS = 'CLEAR_CROP_GENUS';

//PRODUCT_CATEGORY 
export const SELECT_PRODUCT_CATEGORY = 'SELECT_PRODUCT_CATEGORY';
export const PRODUCT_CATEGORY_UPDATE = 'PRODUCT_CATEGORY_UPDATE';
export const PRODUCT_CATEGORY_CREATE = 'PRODUCT_CATEGORY_CREATE';
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';
export const DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY';
export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';
export const CLEAR_PRODUCT_CATEGORY = 'CLEAR_PRODUCT_CATEGORY';

export const WIALON_SYNC_FIELDS = 'WIALON_SYNC_FIELDS';
export const WIALON_GET_TOKEN = 'WIALON_GET_TOKEN';
export const WIALON_GET_UNITS = 'WIALON_GET_UNITS';
export const WIALON_SAVE_TOKEN = 'WIALON_SAVE_TOKEN';
export const WIALON_DELETE_TOKEN = 'WIALON_DELETE_TOKEN';
export const WIALON_SYNCHING = 'WIALON_SYNCHING';
export const GET_TRACKS = 'GET_TRACKS';
export const GET_TRACKER_ACTIVITY = 'GET_TRACKER_ACTIVITY';
export const CLEAR_TRACKER_ACTIVITY = 'CLEAR_TRACKER_ACTIVITY';
export const SET_SELECTED_TRACKS = 'SET_SELECTED_TRACKS';
export const ADD_SELECTED_TRACK = 'ADD_SELECTED_TRACK';
export const SET_TRACK_MIN_LENGHT = 'SET_TRACK_MIN_LENGHT';
export const SET_TRACK_MAX_AVG_SPEED = 'SET_TRACK_MAX_AVG_SPEED';

export const FETCH_UPDATES = 'FETCH_UPDATES';
export const CLEAR_UPDATES = 'CLEAR_UPDATES';
export const EXECUTE_UPDATES = 'EXECUTE_UPDATES';
