export const SPRAY = 'SPRAY';
export const SPRAY_PLAN = 'SPRAY_PLAN';
export const SPRAYER_ACTIVITIES = [SPRAY,SPRAY_PLAN]

export const GENERAL = 'GENERAL';
export const GENERAL_PLAN = 'GENERAL_PLAN';
export const FERTILIZE_IRRIGATION = 'FERTILIZE_IRRIGATION';
export const FERTILIZE_IRRIGATION_PLAN = 'FERTILIZE_IRRIGATION_PLAN';
export const WATERSOURCE_ACTIVITES = [FERTILIZE_IRRIGATION,FERTILIZE_IRRIGATION_PLAN]
export const VARIETY_ACTIVITES = [GENERAL,GENERAL_PLAN];

export const HARVEST = 'HARVEST';
export const MARKET = 'MARKET';
export const PROCUREMENT = 'PROCUREMENT';
export const PEST_MONITOR = 'PEST_MONITOR';

export const PESTICIDE = 'PESTICIDE';
export const VARIETY = 'VARIETY';
export const DISINFECTANT = 'DISINFECTANT';
export const COMPOST = 'COMPOST';

export const FERTILIZER = 'FERTILIZER';
export const WATER = 'WATER';
export const WORKER = 'WORKER';
export const CONTRACTOR = 'CONTRACTOR';
export const WORKER_GROUP = 'WORKER_GROUP';
export const EQUIPMENT = 'EQUIPMENT';
export const ACCESSORY = 'ACCESSORY';

//SPRAY_PLAN, , ROOT,  GENERAL_PLAN, REPORTS, FERTILIZE_IRRIGATION_PLAN, PEST_MONITOR, PROCUREMENT


export const ACTIVITY_TYPES = [GENERAL,SPRAY, FERTILIZE_IRRIGATION, HARVEST, MARKET, PEST_MONITOR ]
export const ACTIVITY_PLAN_TYPES = [GENERAL_PLAN,SPRAY_PLAN, FERTILIZE_IRRIGATION_PLAN ]
export const REPORT_ACTIVITY_TYPES = ACTIVITY_TYPES.concat([PROCUREMENT])

export const GUIDANCE_TYPES = [GENERAL,GENERAL_PLAN, SPRAY, SPRAY_PLAN, FERTILIZE_IRRIGATION, FERTILIZE_IRRIGATION_PLAN, MARKET, HARVEST ]

export const EXECUTORS = [WORKER,WORKER_GROUP,CONTRACTOR];

export const HOUR_ACTIVITIES = [SPRAY_PLAN, SPRAY, MARKET]
export const PERCENTAGE_ACTIVITIES = [SPRAY_PLAN, SPRAY, GENERAL, GENERAL_PLAN]
export const DUPLICATE_FIELD_ACTIVTIES = [HARVEST, MARKET]

