export const SPRAY = 'SPRAY';
export const SPRAY_PLAN = 'SPRAY_PLAN';

export const GENERAL = 'GENERAL';
export const GENERAL_PLAN = 'GENERAL_PLAN';
export const PLANT = 'PLANT';
export const FERTILIZE_IRRIGATION = 'FERTILIZE_IRRIGATION';
export const FERTILIZE_IRRIGATION_PLAN = 'FERTILIZE_IRRIGATION_PLAN';

export const HARVEST = 'HARVEST';
export const MARKET = 'MARKET';
export const PROCUREMENT = 'PROCUREMENT';
export const PEST_MONITOR = 'PEST_MONITOR';


export const PESTICIDE = 'PESTICIDE';
export const VARIETY = 'VARIETY';
export const DISINFECTANT = 'DISINFECTANT';
export const COMPOST = 'COMPOST';


export const FERTILIZER = 'FERTILIZER';
export const WATER = 'WATER';
export const WORKER = 'WORKER';
export const CONTRACTOR = 'CONTRACTOR';
export const WORKER_GROUP = 'WORKER_GROUP';
export const EQUIPMENT = 'EQUIPMENT';
//SPRAY_PLAN, , ROOT,  GENERAL_PLAN, REPORTS, FERTILIZE_IRRIGATION_PLAN, PEST_MONITOR, PROCUREMENT


export const ACTIVITY_TYPES = [GENERAL,SPRAY,PLANT, FERTILIZE_IRRIGATION, HARVEST, MARKET ]